name: ${name}
main: com.precipicegames.zeryl.survivalrun.SurvivalRun
version: ${version}
commands:
    settube:
        description: Sets one of the possible spawn points
        usage: |
            /<command> - Sets one of the possible spawn points
    sendplayers:
      description: Sends players to spawn points
      usage: |
         /<command> - Sends players to spawn points
    deaths:
      description: Lists who has died
      usage: |
        /<command> - Lists out who has died
permissions:
    example.perm:
        description: What this perm does
        default: op