name: ${name}
main: com.precipicegames.zeryl.survivalrun.SurvivalRun
version: ${version}
commands:
    toggle:
        description: Command Description
        usage: |
            /<command> - Toggles switch at announcer booth
permissions:
    example.perm:
        description: What this perm does
        default: op