name: ${name}
main: com.precipicegames.zeryl.survivalrun.SurvivalRun
version: ${version}
commands:
    examplecommand:
        description: Command Description
        usage: |
            /<command> command parms - Command Description
permissions:
    example.perm:
        description: What this perm does
        default: op